FDTD/engine_multithread.cpp, FDTD/engine_sse.cpp
The x86/SSE specific code for Flush-To-Zero is only used when
SSE_CORRECT_DENORMALS is not defined. Guarding the include allows the
code to compile on e.g. ARM.
Signed-off-by: Stefan Brüns <stefan.bruens@rwth-aachen.de>
=> Guard xmmintrin.h include so it is only used when necessary

Common/processmodematch.cpp, FDTD/extensions/operator_ext_tfsf.cpp, FDTD/operator.cpp, tools/sar_calculation.cpp
In case the code is build with -std=c++11, there may be conflicting
definitions of isnan/isinf vs std::isnan/std::isinf, due to the using
namespace std directive.
This happens for glibc versions 2.25 and older, see
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=48891 for details.
Signed-off-by: Stefan Brüns <stefan.bruens@rwth-aachen.de>
=> Fix build error due to ambigous overload of isnan/isinf

matlab/setup.m
If the command returned two lines (in the case that there were two copies of hdf5.h on the system, then the system got confused. Also updated the options to the mkoctfile command to concatenate the strings separately. This fixes Issue #36 (at least on my Debian testing installation)
=> Modify the find command to return only one line.

nf2ff/nf2ff_calc.cpp
This fixes a bug in nf2ff. When using mirror planes, fields and mesh
lines are mirrored in place. Mesh lines must be restored after the
calculation of a single frequency point. Otherwise, the far field at
every even frequency point is incorrect.
=> nf2ff: restore mesh lines after mirroring

python/Tutorials/RCS_Sphere.py
For more details please have a look at #58
=> Fix missing deg2rad in RCS sphere tutorial (python interface)

python/openEMS/openEMS.pyx
Solved the issue #59
Calling the run function multiple times caused an error
=> Fix crash on recalling run() with enabled cleanup

matlab/RunOpenEMS.m
A simulation path that contains a whitespace character (and probably a lot of other characters that have special meanings inside a shell) leads to an scp failure when the simulation data is copied back to the host machine. Replacing [pwd '/'] by just './' as the back-copying destination fixes this problem.
=> Allow whitespaces in simulation path (remote)

openEMS.sh
1. use Bourne shell to prevent unnecessary dependencies
2. fix $@ to handle arguments with spaces properly
=> Fixes in openEMS.sh

openems.cpp, openems.h, python/openEMS/openEMS.pxd, python/openEMS/openEMS.pyx
For some experiments, I required the step excitation and i just exposed the additional functions to the python API. I did not look into the CustomExcite, probably requires some String casting between C++ and Python and I did not use it for now.
=> Expose sinusoidal, dirac pulse and step pulse excitation to the Python API.

python/openEMS/openEMS.pxd, python/openEMS/openEMS.pyx
Added support to the Python API for:
- `DebugMaterial()`
- `DebugOperator()`
- `DebugBox()`
- `DebugCSX()`
Tested and seems to work fine.
=> Expose Debugs to Python API

python/openEMS/ports.py
Accroding to NumPy's development team, "for a long time, np.int has been an alias of the builtin int. This is repeatedly a cause of confusion for newcomers, and existed mainly for historic reasons."
This and many other aliases have been deprecated since NumPy v1.20.0, and at this point they've been completely removed. Replace "np.int" with "int" allows ports.py to run again.
=> python/ports.py: replace deprecated "np.int" with "int".

python/openEMS/automesh.py
This PR provides `mesh_estimate_cfl_timestep`, a function that accepts a `CSRectGrid` mesh and provides a crude estimate of the maximum CFL time step (in seconds), assuming vacuum propagation. Since adding materials with different permittivities / permeabilities will simply slow the propagation of EM waves in the medium, this is actually an underestimation of the true maximum time step.
=> Implement mesh_estimate_cfl_timestep

python/openEMS/openEMS.pyx
Currently, running openEMS's example Python scripts on macOS always fails with the following error:
$ python3 MSL_NotchFilter.py
Traceback (most recent call last):
File "/Users/gentoo/code/openEMS-Project/openEMS/python/Tutorials/MSL_NotchFilter.py", line 103, in <module>
FDTD.Run(Sim_Path, cleanup=True)
File "openEMS/openEMS.pyx", line 489, in openEMS.openEMS.openEMS.Run
AssertionError
This is caused by an oversight of an assertion in openEMS.pyx:
os.chdir(sim_path)
assert os.getcwd() == sim_path
The problem here is that "sim_path" is not a canonical path name, so the assertion would fail if the path we're switching into contains a symbolic link. This problem affects all operating systems, it's not limited to macOS. But on macOS, the problem is especially serious, since macOS's "/tmp" is …
=> openEMS.pyx: check canonical path in assert, close #113.

openems.cpp, tools/CMakeLists.txt, tools/signal.cpp, tools/signal.h
<del>Note: This is the first draft for comments and reviews, do not merge.</del>
Update: It's now merge-ready, support for Windows's native `ConsoleCtrlHandler` has also been added.
Currently, openEMS doesn't have any special code to handle SIGINT (which is raised by pressing Control-C). By default, the program is terminated without saving data. This worked okay in the past, but now its limitations are becoming obvious.
1. When openEMS is used as a Python module, Control-C stops working because SIGINT is now managed by Python in order to generate KeyboardInterrupt exceptions, normally this isn't a problem, but if we are running an external C++ (Cython) function such as openEMS, the Python interpreter mainloop has no control until we return. As a result, SIGINT is received but never …
=> Handle SIGINT for openEMS and Python, with graceful exit support.

FDTD/engine.cpp, FDTD/engine_sse.cpp, FDTD/engine_sse_compressed.cpp
The original update equations in the FDTD engine have extremely long lines. I found they're difficult to read and work with. This patch inserts line breaks, and aligns all array indexes by x/y/z coordinates to make it easy to visually compare during debugging.
This commit also serves as the foundation of the mentioned future work in Issue #100.
=> FDTD: reformat code of update equations.

nf2ff/CMakeLists.txt
Fixes https://github.com/thliebig/openEMS-Project/issues/190
As of recent, `nf2ff` has been failing to compile with the latest version of boost (1.84.0):
```
In file included from /tmp/openEMS-Project/openEMS/nf2ff/nf2ff.cpp:19:
In file included from /tmp/openEMS-Project/openEMS/nf2ff/nf2ff_calc.h:26:
In file included from /usr/local/include/boost/thread.hpp:24:
In file included from /usr/local/include/boost/thread/future.hpp:31:
In file included from /usr/local/include/boost/thread/detail/invoker.hpp:32:
/usr/local/include/boost/thread/csbl/tuple.hpp:19:18: error: no member named 'tuple' in namespace 'std'
using ::std::tuple;
~~~~~~~^
/usr/local/include/boost/thread/csbl/tuple.hpp:21:18: error: no member named 'make_tuple' in namespace 'std'
using ::std::make_tuple;
~~~~~~~^
```
[They …
=> Set C++ version for boost thread

FDTD/extensions/engine_ext_lumpedRLC.cpp, FDTD/extensions/operator_ext_lumpedRLC.cpp, FDTD/extensions/operator_ext_lumpedRLC.h
The original contributor used "uint" in all code, which is a non-standard language extension that doesn't exist in ISO C or ISO C++, and causes build failures on macOS as reported by PR #144. Replace all "uint" with "unsigned int" for standard conformance to maximize portability.
=> lumpedRLC: replace all "uint" to "unsigned int".

CMakeLists.txt, main.cpp, openems.cpp, openems.h, python/openEMS/openEMS.pxd, python/openEMS/openEMS.pyx, tools/global.cpp, tools/global.h
Currently, the openEMS command-line argument parsing has two limitations.
1. If a new module is added into openEMS and that module accepts runtime options, one must change the main openems.cpp to add one new API per option, decreasing code modularity - especially if an option is only used by a single module. This is unsustainable in the long run. The in-development Tiling engine is expected to accept 3 to 4 options.
2. When we're running as a shared library (used by Python binding), if one wants to pass runtime options from Python, one must change the main openems.cpp to add one new API per option. This is again unsustainable. For example, currently there's no way to change the simulation engine via Python because of the lack of APIs.
To overcome these limitations, this commit completely …
=> Completely Rewrite Command-Line Argument Parsing, and Support Passing All Arguments via Python

FDTD/extensions/engine_ext_dispersive.cpp, FDTD/extensions/engine_ext_dispersive.h, FDTD/extensions/engine_ext_excitation.cpp, FDTD/extensions/engine_ext_excitation.h, FDTD/extensions/engine_ext_lorentzmaterial.cpp, FDTD/extensions/engine_ext_lorentzmaterial.h, FDTD/extensions/engine_ext_lumpedRLC.cpp, FDTD/extensions/engine_ext_lumpedRLC.h, FDTD/extensions/engine_ext_mur_abc.cpp, FDTD/extensions/engine_ext_mur_abc.h, FDTD/extensions/engine_ext_upml.cpp, FDTD/extensions/engine_ext_upml.h, FDTD/extensions/engine_extension_dispatcher.h
In openEMS, all extensions are subclasses from the abstract `Engine_Extension` to implement features like `Engine_Extension::Apply2Voltages()`. When an `Engine_Extension` is created, it accepts a pointer to `Engine`. Simulation data is taken from the `Engine` using virtual functions like `Engine::GetVolt()`.
Because virtual functions prevent the compiler from inlining the code, in order to select the non-virtual functions, each extension repeats the same simulation code repeated many times using non-virtual subclass engine functions in a big if/else check, e.g. 2 different `Apply2Voltages()`, one calls `Engine::GetVolt()`, another calls `Engine_sse::GetVolt()`. This led to code duplication and poor readability.
I found it's extremely difficult to do any development within these Extensions …
=> Eliminate Code Duplication in Engine_Extension classes using a Helper Macro

python/openEMS/openEMS.pyx
Fix the issue encounter by a user, see [here](https://github.com/thliebig/openEMS-Project/discussions/227#discussioncomment-11202974).
PS: This does exactly the same as #157 , I did not manage to mix my commits into a single one due to the merge in the middle, so I just made a new branch. Not a professional software developer, sorry.
=> Fix assertion in `Run` when symlinks are present

CMakeLists.txt
This PR contains two changes.
In VTK 9+, components vtkIOXML, vtkIOGeometry, vtkIOLegacy, vtkIOPLY, etc, have been renamed to IOXML, IOGeometry, IOLegacy, IOPLY, etc. So use the new name if VTK 9+ is detected.
The `VTK_USE_FILE` is no longer used starting with 8.90.
=> Fix VTK Deprecation Warning in CMake

CMakeLists.txt
It turns out that `find_package(VTK)` without any component has some side-effects that interacts with Boost, causing nf2ff build failures. This problem doesn't seem to show up if openEMS is built separately, but will appear if the entire project is built together.
To fix the problem, instead we use:
find_package(VTK COMPONENTS CommonCore QUIET)
If VTK 9 is installed, CommonCore can be found and VTK 9's branch is executed. It's marked as QUIET so this failure doesn't generate fatal error messages on the screen. If VTK 8 is installed (or no VTK is installed), VTK 8's branch is executed, so its behavior on old systems should be exactly the same.
=> CMakeLists.txt: fix VTK regression again.

python/setup.py
On Debian 11, running openEMS via Python produces the following error:
ImportError: numpy.core.multiarray failed to import
This is a binary compatibility problem that should've never happened. But it did. Why? Because setup.py requires NumPy 1.26, but Debian only has NumPy 1.24. Python finds no system package that can satisfy this requirement so download binaries that from PyPI instead. But now we have NumPy v2 incompatible with the rest of the system, creating the binary compatibility problem. It's exactly why PyPI packages should never be mixed outside a virtualenv. Same problems exist for h5py and cython as well. although there's no compatibility problem per se, at least, not yet.
These version requirements were introduced by in commit 5bc31d0 ("add missing package python …
=> python/setup.py: drop minimum version requirements, close #165.

python/openEMS/openEMS.pyx, tools/global.cpp
After commit 3c4e802638d4 ("Completely Rewrite Command-Line Argument Parsing"), the "verbose" option was assigned an implicit value (i.e. the value used for "-v" without an explicit number), but not a default value (i.e. the value used if no "-v" is given). This commit assigns a default value of 0 for logical consistency, and to allow the help message to show the default verbose value correctly.
=> tools/global.cpp: assign default verbose value.

FDTD/extensions/engine_ext_mur_abc.cpp, FDTD/extensions/engine_ext_mur_abc.h, FDTD/extensions/operator_ext_mur_abc.h
This commit improves the readability of Mur ABC (as highlighted [1]) by doing the following:
1. The meaning of most member variables in `Operator_Ext_Mur_ABC` are now explained in the comments.
2. Variables `ny`, `nyP`, and `nyPP` are renamed to `dir1`, `dir2` and `dir3` so they're self-explanatory.
3. The extension update loops use arrays as loop variables, including array `pos`, `pos_shift`, and they're combined with counters including `lineX`, `m_start`, and `m_numX`. This makes the loop structure difficult to understand, as it's difficult to see which variable is in control. The commit rewrites the loop using the idiomatic `i` and `j` as loop variables, which is then used to derive `pos[3]` and `pos_shift[3]`.
[1] https://github.com/thliebig/openEMS-Project/discussions/273
=> Improve Readability of Operator_Ext_Mur_ABC and Engine_Ext_Mur_ABC

python/openEMS/ports.py
In case one uses a single string/filename in the port, looping over `self.{U,I}_filenames` will cause it to loop over the characters in the filename rather than the list of files, causing an index out of bounds error.
This scenario is already handled in `UI_data` with `fns`, hence we just re-use this in ReadUI, such that we have the filenames
iterable in all the cases
=> python/ports: Fix single filenames for ReadUI

tools/arraylib/impl/allocator.h
The error message was:
```
...\openEMS\tools\arraylib\impl\allocator.h(70,9): error C2440: '=': cannot convert from 'void *' to 'T *' [...\build\openEMS-prefix\src\openEMS-build\openEMS.vcxproj] [...\build\openEMS.vcxproj]
...\openEMS\tools\arraylib\impl\allocator.h(70,9): error C2440: with [...\build\openEMS-prefix\src\openEMS-build\openEMS.vcxproj] [...\build\openEMS.vcxproj]
...\openEMS\tools\arraylib\impl\allocator.h(70,9): error C2440: [ [...\build\openEMS-prefix\src\openEMS-build\openEMS.vcxproj] [...\build\openEMS.vcxproj]
...\openEMS\tools\arraylib\impl\allocator.h(70,9): error C2440: T=float [...\build\openEMS-prefix\src\openEMS-build\openEMS.vcxproj] [...\build\openEMS.vcxproj]
...\openEMS\tools\arraylib\impl\allocator.h(70,9): error C2440: ] …
```
=> Fix build error on MSVC in allocator.

.github/workflows/ci.yml, CMakeLists.txt, python/setup.py
This Pull Request contains the following changes. Merging these changes would resolve multiple CI/CD build failures, and also prepare the project for the upcoming CMake 4.0 (only macOS's Homebrew has rolled it out, but it's expected to arrive to more systems in the upcoming years).
The following fparser Pull Requests must be merged *before* merging this PR, otherwise CI/CD would still fail on macOS due to the missing fixes.
* https://github.com/thliebig/fparser/pull/6
* https://github.com/thliebig/CSXCAD/pull/62
* https://github.com/thliebig/QCSXCAD/pull/18
* https://github.com/thliebig/AppCSXCAD/pull/14
In CMake 4, 3.10 is deprecated and 3.5 has been removed. Use 3.0...3.10 so all of these versions are acceptable as minimum version.
The Python module requires at least C++11, otherwise …
=> Fix CI/CD builds on Ubuntu 14.04, macOS, and FreeBSD
